baseURL: https://rmi-pacta.github.io/
title: PACTA Tech Blog
author: RMI
copyright: Open-source <a class="text-muted text-decoration-none" href="https://github.com/RMI-PACTA/rmi-pacta.github.io/LICENSE.md">MIT</a>
  Licensed.
timeZone: Europe/Berlin
defaultContentLanguage: en
defaultContentLanguageInSubdir: no
theme: hugo-bootstrap-theme
disableHugoGeneratorInject: yes
enableRobotsTXT: yes
enableGitInfo: yes
enableEmoji: yes
frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    - :fileModTime
    - :default
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
permalinks: {}
module:
  hugoVersion:
    extended: yes
    max: ''
    min: 0.99.1
  mounts:
    - source: assets
      target: assets
    - source: static
      target: static
