# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "Welcome to the PACTA technical team's blog. We create open-source tools and software to help align financial flows with climate goals"
images = ['images/logo_stacked.svg', 'images/logo_primary.svg']
mainMenuLogo = "images/logo_stacked.svg"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
alert = false
alertDismissable = true
alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

# Pre-footer
footerAbout = true
footerAboutTitle = "We are the PACTA technical team :-)"
footerAboutText = "We create tools and software to help fight the climate crisis."

[options]
  bootStrapJs = true
  breadCrumb = true
  listCategoryFilter = true
  listTagFilter = true
